### ISSUE TITLE
Cocoapods?

### ISSUE THREAD

**Issue by furkankadioglu** [priore/DPPickerManager#1]
Hello,

Can we use with cocoapods?

**Comment by ibolat38** [comment]
'open class' yani DPPickerManager.swift dosyasını direkt sürükle bırak projene çalışır.

**Comment by priore** [comment]
yes

`pod 'DPPickerManager'`

or

`pod 'DPPickerManager', :git => 'https://github.com/priore/DPPickerManager.git'`
