### ISSUE TITLE
Doesn't work in swift

### ISSUE THREAD

**Issue by Gargo** [priore/DPPickerManager#7]
Imported via cocoapods.

Your first example for picker with strings:
`'shared' is inaccessible due to 'internal' protection level`

**Comment by federik21** [comment]
You will need to instance the class now, I think. But the code is not working for me because UIImage(named: "ic_close") is giving nil

**Comment by svastven** [comment]
@federik21 I have the same problem

**Comment by priore** [comment]
update commit 767935adb655de1ab8b392bc5815ecee68319c58
thanks to @uiue
